// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHJpT3dX_KFpR2SAgeGl5jqdxolo1q58',
    appId: '1:1076131602282:web:bfac488a881bb69527cf13',
    messagingSenderId: '1076131602282',
    projectId: 'flutter-chat-app-3786c',
    authDomain: 'flutter-chat-app-3786c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3786c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fVrBbC2uyANFP77rC3l2J6cHElE2eRA',
    appId: '1:1076131602282:android:44d990adfdf57a7f27cf13',
    messagingSenderId: '1076131602282',
    projectId: 'flutter-chat-app-3786c',
    storageBucket: 'flutter-chat-app-3786c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHJpT3dX_KFpR2SAgeGl5jqdxolo1q58',
    appId: '1:1076131602282:web:27a339ffd8e48b0927cf13',
    messagingSenderId: '1076131602282',
    projectId: 'flutter-chat-app-3786c',
    authDomain: 'flutter-chat-app-3786c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3786c.firebasestorage.app',
  );
}
